### PR TITLE
Replace pkg_resources usage

### PR DESCRIPTION
**Pull request by gforcada**
See https://github.com/plone/Products.CMFPlone/issues/4126

### CODE REVIEW

File: docs/conf.py [hunk 1]
```diff
@@ -51,10 +51,11 @@
 # other places throughout the built documents.
 #
 # The short X.Y version.
-version = '%s.%s' % tuple(rqmt.version.split('.')[:2])
+version = '%s.%s' % tuple(rqmt.split('.')[:2])
 # The full version, including alpha/beta/rc tags.
 release = rqmt.version
```
Comment (davisagli) [inline docs/conf.py:56]: This will break with `AttributeError: 'str' object has no attribute 'version'` because you already got `.version` on line 21, which returns a `str`

**Review by davisagli — CHANGES_REQUESTED** [review]

File: docs/conf.py (hunk 1 above)
Comment (gforcada) [reply docs/conf.py]: Ouch, right, thanks for noticing it!

**Comment by gforcada** [comment]
@mauritsvanrees tests are failing due to latest `zc.buildout==4.1` version, if on `tox.ini` one pins `zc.buildout==4.0` then it works

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks.

I have just released zc.buildout 4.1.1 with a fix.  If you rerun the failed checks in a few minutes, I think the tests will pass.

**Comment by mauritsvanrees** [comment]
[This test run](https://github.com/zopefoundation/Products.GenericSetup/actions/runs/13651874935/job/38202364157) passed on Python 3.8, but failed on 3.9 and higher with something like:

```
  File "/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/.tox/py312/lib/python3.12/site-packages/zc/buildout/buildout.py", line 1165, in _maybe_upgrade
    if not inspect.getfile(sys.modules[project]).startswith(dist.location):
                                                            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'
```

This could be yet another fix in `zc.buildout`.  Or we use `setuptools` 75.8.2, which is better at finding packages.  So that is what I did in commit c4b0ab37838e4924d5060e1f90db415833effbe9.  That leads to [this test run](https://github.com/zopefoundation/Products.GenericSetup/actions/runs/13664487074) which passes for all environments, except Python 3.8.  The reason is simple: neither the lastest zc.buildout nor the latest setuptools works on Python 3.8.

I tried locally without restraints in tox, so just require setuptools, zc.buildout (and wheel) without any minimum version, but then 3.9, 3.10, and 3.11 failed.

So next up: drop Python 3.8 support.  I suppose we are fine with that.
I will run zope.meta here.

**Comment by mauritsvanrees** [comment]
The tests are green now.

But the Python 3.8 tests are required and pending.  This should be removed from the branch protection rules now that we have dropped support.  I think I can do this myself, but wanted an approval first.

**Comment by gforcada** [comment]
Python 3.8 is being retired in both Zope and Plone, so I would say this is totally fine 👍🏾

**Comment by dataflake** [comment]
@gforcada I am confused by the package management related changes. Did you run the zope.meta package configuration script against the repository? If yes then your version of zope.meta must be seriously outdated.

**Review by dataflake — CHANGES_REQUESTED** [review]
Please remove all packaging-related changes that are handled by zope.meta here, those are bad. Looks like you either ran an outdated version or you just manually changed files that are under zope.meta control.

**Comment by mauritsvanrees** [comment]
I replaced this by PR #136, which retains only the relevant commits, and squashes them together.
